name: sims_mobile
description: SIMS Mobile - Smart Attendance App SMA Negeri 1 Gianyar
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # HTTP client dengan interceptor
  dio: ^5.7.0

  # Token storage yang aman (Keystore/Keychain)
  flutter_secure_storage: ^9.2.1

  # Device ID — ANDROID_ID / identifierForVendor (Anti-Titip Absen)
  device_info_plus: ^10.1.0

  # GPS + isMocked detection
  geolocator: ^11.0.0

  # Kamera selfie
  camera: ^0.10.5+9

  # Manajemen permission runtime
  permission_handler: ^11.3.1

  # State management
  provider: ^6.1.2

  # Formatting tanggal & locale Indonesia
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0F2460"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true
  web:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
